/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 knob.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/models/table/knob.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="knob" position={[0, 0.18, 0]} scale={0.1}>
          <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.knobMat} />
          <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials.knobBallMat} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/table/knob.glb')
