/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 circular-garden.glb --keepgroups --keepnames
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/models/gardens/circular-garden.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="trees-dark_0002_Layer-1---2" geometry={nodes['trees-dark_0002_Layer-1---2'].geometry} material={materials['trees-dark_0002_Layer-1---2']} position={[-31.55, 1.84, -41.27]} rotation={[Math.PI / 2, 0, -0.28]} scale={11.02} />
        <mesh name="trees-dark_0002_Layer-1---2001" geometry={nodes['trees-dark_0002_Layer-1---2001'].geometry} material={materials['trees-dark_0002_Layer-1---2']} position={[-25.27, 2.47, -34.55]} rotation={[Math.PI / 2, 0, 0]} scale={16.59} />
        <mesh name="trees-dark_0002_Layer-1---2005" geometry={nodes['trees-dark_0002_Layer-1---2005'].geometry} material={materials['trees-dark_0002_Layer-1---2']} position={[-6.67, -1.42, -13.63]} rotation={[Math.PI / 2, 0, 0]} scale={7.18} />
        <mesh name="trees-dark_0002_Layer-1---2002" geometry={nodes['trees-dark_0002_Layer-1---2002'].geometry} material={materials['trees-dark_0002_Layer-1---2']} position={[-9.71, -1.43, -16.93]} rotation={[Math.PI / 2, 0, 0]} scale={7.18} />
        <mesh name="trees-dark_0002_Layer-1---2003" geometry={nodes['trees-dark_0002_Layer-1---2003'].geometry} material={materials['trees-dark_0002_Layer-1---2']} position={[7.78, -1.43, -17.4]} rotation={[Math.PI / 2, 0, 0]} scale={7.18} />
        <mesh name="trees-dark_0003_Layer-1---3" geometry={nodes['trees-dark_0003_Layer-1---3'].geometry} material={materials['trees-dark_0003_Layer-1---3']} position={[6.32, -3.06, -15.91]} rotation={[Math.PI / 2, 0, 0.01]} scale={5.58} />
        <mesh name="trees-dark_0003_Layer-1---3001" geometry={nodes['trees-dark_0003_Layer-1---3001'].geometry} material={materials['trees-dark_0003_Layer-1---3']} position={[-6.78, -3.06, -17.26]} rotation={[Math.PI / 2, 0, 0.01]} scale={5.58} />
        <mesh name="lawn" geometry={nodes.lawn.geometry} material={materials.lawn} position={[0, -7.4, -49.77]} rotation={[Math.PI / 2, 0, 0]} scale={42.87} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/gardens/circular-garden.glb')
