/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 default-structure.gltf --transform -R 8192 --keepgroups --keepnames
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model({ context, ...props }) {
  const { nodes, materials } = useGLTF(
    "/assets/models/buildings/default-structure.glb"
  );

  //

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group transformLink={{ id: "wallRoomLink", movementMultiplier: 14 }}>
          <group name="GROUP_ROOM" position={[8.1, 1.25, -1.42]}>
            <mesh
              name="beam-room"
              geometry={nodes["beam-room"].geometry}
              material={materials.beamMatRoom}
              position={[-0.2, -1.25, 1.42]}
            />
            <mesh
              name="floor-room"
              geometry={nodes["floor-room"].geometry}
              material={materials.roomFloorMat}
              position={[-0.2, -1.25, 1.42]}
            />
            <mesh
              name="red-carpet"
              geometry={nodes["red-carpet"].geometry}
              material={materials["red-carpet"]}
              position={[-0.2, -1.25, 1.42]}
            />
            <mesh
              name="vines"
              geometry={nodes.vines.geometry}
              material={materials.HangingVineDecal}
              position={[-0.2, -1.25, 1.42]}
            />
            <mesh
              name="wall-second-room"
              geometry={nodes["wall-second-room"].geometry}
              material={materials.wallRoomMat}
              position={[-0.2, -1.25, 1.42]}
            />
          </group>
        </group>
        <group name="palm" position={[-3.33, 0.03, -4.06]}>
          <mesh
            name="dirt"
            geometry={nodes.dirt.geometry}
            material={materials["Dirt.001"]}
            position={[3.33, -0.32, 4.06]}
          />
          <mesh
            name="palm-fronds"
            geometry={nodes["palm-fronds"].geometry}
            material={materials.PalmMat2}
            position={[3.33, -0.32, 4.06]}
          />
          <mesh
            name="pot"
            geometry={nodes.pot.geometry}
            material={materials["Pot.001"]}
            position={[3.33, -0.32, 4.06]}
          />
        </group>

        <group transformLink={{ id: "wallWindowLink", movementMultiplier: 14 }}>
          <group name="GROUP_WINDOW" position={[0.9, -0.29, -0.04]}>
            <mesh
              name="beam-window"
              geometry={nodes["beam-window"].geometry}
              material={materials.beamMatWindow}
              position={[-7.55, 0.29, 0.04]}
            />
            <mesh
              name="floor-window"
              geometry={nodes["floor-window"].geometry}
              material={materials.wallFloorMat}
              position={[-7.55, 0.29, 0.04]}
            />
            <mesh
              name="wall-window"
              geometry={nodes["wall-window"].geometry}
              material={materials["wallWindowMat.001"]}
              position={[-7.55, 0.29, 0.04]}
            />
            <mesh
              name="yellow-carpet"
              geometry={nodes["yellow-carpet"].geometry}
              material={materials["yellow-carpet"]}
              position={[-7.55, 0.29, 0.04]}
            />
          </group>
        </group>
        {context !== "mini" && (
          <group name="GROUP_HIDDEN">
            <mesh
              name="front-wall-extension-left"
              geometry={nodes["front-wall-extension-left"].geometry}
              material={materials.windowWallExtensionLeft}
            />
            <mesh
              name="front-wall-extension-right"
              geometry={nodes["front-wall-extension-right"].geometry}
              material={materials.windowWallExtensionRight}
            />
            <mesh
              name="wall-back"
              geometry={nodes["wall-back"].geometry}
              material={materials.backWallmat}
            />
          </group>
        )}
        <mesh
          name="floor-main"
          geometry={nodes["floor-main"].geometry}
          material={materials.floorMat}
        />
        <mesh
          name="wall-front001"
          geometry={nodes["wall-front001"].geometry}
          material={materials.frontWallMat}
        />
        <mesh
          name="planter"
          geometry={nodes.planter.geometry}
          material={materials.planterTex}
        />
        <mesh
          name="fern"
          geometry={nodes.fern.geometry}
          material={materials.fernTex}
        />
        <mesh
          name="windowFrame1"
          geometry={nodes.windowFrame1.geometry}
          material={materials.windowFrame1}
        />
        <mesh
          name="windowFrame2"
          geometry={nodes.windowFrame2.geometry}
          material={materials.windowFrame2}
        />
        <group transformLink={{ id: "alcoveLink", movementMultiplier: 14 }}>
          <mesh
            name="alcove"
            geometry={nodes.alcove.geometry}
            material={materials.AlcoveMaterial}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/buildings/default-structure.glb");
